default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_blog_app_development
  username: postgres
  password: kandy

  
test:
  <<: *default
  database: rails_blog_app_test
  username: postgres
  password: kandy

production:
  <<: *default
  database: rails_blog_app_production
  username: postgres
  password: kandy
